version: "3.7"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./code:/code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8090:80"

  database:
    image: mysql:5.7
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=laravel"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD="
      - "MYSQL_ROOT_PASSWORD="
    ports:
      - "33061:3306"
      
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: botbeh-wYbvow-sebwu9
    ports:
      - 8888:80

  php:
    image: php:7.4-fpm-alpine
    working_dir: /code
    volumes:
      - ./code:/code

  node:
    image: node:latest
    working_dir: /code
    volumes:
      - ./code:/code
    ports:
      - "3000:3000"
      - "3001:3001"
    tty: true
